api/urls.py
from django.urls import include, path
from rest_framework.routers import DefaultRouter
from rest_framework.schemas import get_schema_view
from rest_framework.documentation import include_docs_urls

from .views import OrgViewSet, AssetViewSet


router = DefaultRouter()
router.register('v1/org', OrgViewSet, 'api_org_list')
router.register('v1/asset', AssetViewSet, 'api_asset_list')
schema_view = get_schema_view(title='Assma API',
                              description='An API to query orgs or assets',
                              version=1
                              )


urlpatterns = [
    path('api/', include(router.urls)),
    path('api/schema/', schema_view),
    path('api/docs/', include_docs_urls(title='Assma API')),
]

assma/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('web.urls')),
    path('', include('api.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

web/models.py
from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
import ipaddress
import re
import validators
import socket

class Org(models.Model):

    LEVEL_FEDERAL = 'Federal'
    LEVEL_STATE = 'State'
    LEVEL = [
        (LEVEL_FEDERAL, 'Federal / National level'),
        (LEVEL_STATE, 'State level'),
    ]

    SECTOR_ENERGY = 'Energy, Utilities, Agriculture'
    SECTOR_SECURITY = 'Safety and Security'
    SECTOR_DEFENSE = 'Defense and Intelligence'
    SECTOR_ICT = 'ICT'
    SECTOR_TRANSPORTATION = 'Transportation'
    SECTOR_ADMIN = 'Government Administration'
    SECTOR_EDUCATION = 'Education'
    SECTOR_MEDIA = 'Media, Entertainment'
    SECTOR_FINANCE = 'Finance and Economy'
    SECTOR_SPECIAL = 'Special'
    SECTOR_HEALTH = 'Healthcare'
    SECTOR_MANUFACTURING = 'Manufacturing, Construction'
    SECTOR = [
        (SECTOR_ENERGY, 'Energy, Utilities, Agriculture'),
        (SECTOR_SECURITY, 'Safety and Security'),
        (SECTOR_DEFENSE, 'Defense and Intelligence'),
        (SECTOR_ICT, 'ICT'),
        (SECTOR_TRANSPORTATION, 'Transportation'),
        (SECTOR_ADMIN, 'Government Administration'),
        (SECTOR_EDUCATION, 'Education'),
        (SECTOR_MEDIA, 'Media, Entertainment'),
        (SECTOR_FINANCE, 'Finance and Economy'),
        (SECTOR_SPECIAL, 'Special'),
        (SECTOR_HEALTH, 'Healthcare'),
        (SECTOR_MANUFACTURING, 'Manufacturing, Construction'),
    ]

    name = models.CharField(max_length=255, null=False, unique=True)
    level = models.CharField(max_length=255, choices=LEVEL, default=LEVEL_FEDERAL)
    sector = models.CharField(max_length=255, choices=SECTOR, default=SECTOR_ADMIN)
    tier = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)], default=5)
    comment = models.TextField(blank=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Asset(models.Model):
    TYPE_DOMAIN = 'domain'
    TYPE_IPV4 = 'ipv4'
    TYPE_RANGE4 = 'range4'
    TYPE_NETMASK4 = 'netmask4'
    TYPE_CIDR4 = 'cidr4'
    TYPE_IPV6 = 'ipv6'
    TYPE_RANGE6 = 'range6'
    TYPE_CIDR6 = 'cidr6'
    TYPE = [
        (TYPE_DOMAIN, 'domain'),
        (TYPE_IPV4, 'ipv4'),
        (TYPE_RANGE4, 'range4'),
        (TYPE_NETMASK4, 'netmask4'),
        (TYPE_CIDR4, 'cidr4'),
        (TYPE_IPV6, 'ipv6'),
        (TYPE_RANGE6, 'range6'),
        (TYPE_CIDR6, 'cidr6'),
    ]

    name = models.CharField(max_length=255, null=False, unique=True)
    org = models.ForeignKey(Org, on_delete=models.PROTECT)
    type = models.CharField(max_length=255, choices=TYPE)
    start_ip = models.UUIDField(blank=True)
    end_ip = models.UUIDField(blank=True)
    comment = models.TextField(blank=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def save(self, **kwargs):
        self.clean()
        return super(Asset, self).save(**kwargs)

    def clean(self):
        super(Asset, self).clean()

        if str(self.type) == "ipv4":
            try:
                ipaddress.IPv4Address(str(self.name))
            except:
                raise ValidationError('\"' + self.name + '\" is not a valid ipv4 address')
            self.start_ip = int(ipaddress.IPv4Address(self.name))
            self.end_ip = int(ipaddress.IPv4Address(self.name))

        if str(self.type) == "ipv6":
            try:
                ipaddress.IPv6Address(str(self.name))
            except:
                raise ValidationError('\"' + self.name + '\" is not a valid ipv6 address')
            self.start_ip = int(ipaddress.IPv6Address(self.name))
            self.end_ip = int(ipaddress.IPv6Address(self.name))

        if str(self.type) == "cidr4":
            match = re.search('/', self.name,  )
            if match:
                try:
                    ipaddress.IPv4Network(str(self.name))
                except:
                    raise ValidationError('\"' + self.name + '\" is not a valid ipv4 network address')
                self.start_ip = int(ipaddress.IPv4Network(self.name)[0])
                self.end_ip = int(ipaddress.IPv4Network(self.name)[-1])
            else:
                raise ValidationError('\"' + self.name + '\" is not a valid ipv4 cidr address')

        if str(self.type) == "cidr6":
            try:
                ipaddress.IPv6Network(str(self.name))
            except:
                raise ValidationError('\"' + self.name + '\" is not a valid ipv6 cidr address')
            self.start_ip = int(ipaddress.IPv6Network(self.name)[0])
            self.end_ip = int(ipaddress.IPv6Network(self.name)[-1])

        if str(self.type) == "range4":
            match = re.search('[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}-[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}', self.name,  )
            if match:
                pair = self.name.split("-")
                test = ipaddress.IPv4Address(pair[1]) > ipaddress.IPv4Address(pair[0])
                if test == False:
                    raise ValidationError('\"' + pair[1] + '\" is not higher than \"' + pair[0] + '\" try again!')

                for ip4 in pair:
                    try:
                        ipaddress.IPv4Address(str(ip4))
                    except:
                        raise ValidationError('\"' + ip4 + '\" is not a valid ipv4 address')
                self.start_ip = int(ipaddress.IPv4Address(pair[0]))
                self.end_ip = int(ipaddress.IPv4Address(pair[1]))
            else:
                raise ValidationError('\"' + self.name + '\" is not a valid range4 address, please use a hyphen as a separator eg 1.2.3.4-1.2.3.8')

        if str(self.type) == "range6":
            match = re.search('[0-9a-f:]+-[0-9a-f:]+', self.name, re.I)
            if match:
                pair = self.name.split("-")
                test = ipaddress.IPv6Address(pair[1]) > ipaddress.IPv6Address(pair[0])
                if test == False:
                    raise ValidationError('\"' + pair[1] + '\" is not higher than \"' + pair[0] + '\" try again!')
                for ip6 in pair:
                    try:
                        ipaddress.IPv6Address(str(ip6))
                    except:
                        raise ValidationError('\"' + ip6 + '\" is not a valid ipv6 address')
                self.start_ip = int(ipaddress.IPv6Address(pair[0]))
                self.end_ip = int(ipaddress.IPv6Address(pair[1]))
            else:
                raise ValidationError('\"' + self.name + '\" is not a valid range6 address, please use a hyphen as a separator eg 2001:db8::-2001:db8:0000:0000:0000:0000:0000:00ff')

        if str(self.type) == "netmask4":
            match = re.search('[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}/[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}', self.name,  )
            if match:
                try:
                    ipaddress.IPv4Network(str(self.name))
                except:
                    raise ValidationError('\"' + self.name + '\" is not a valid ipv4 netmask, please use forward slash as separator eg 192.168.10.0/255.255.255.0')
                self.start_ip = int(ipaddress.IPv4Network(self.name)[0])
                self.end_ip = int(ipaddress.IPv4Network(self.name)[-1])
            else:
                raise ValidationError('\"' + self.name + '\" is not a valid ipv4 netmask, please use forward slash as separator eg 192.168.10.0/255.255.255.0')

        if str(self.type) == "domain":
            test = validators.domain(self.name)
            if test != True:
                raise ValidationError('\"' + self.name + '\" is not a valid domain name')

            # remove old lookup results ready for new one
            comment = re.sub('^__.*$', '', self.comment, 0, re.MULTILINE)
            # remove blank lines
            comment = re.sub(r'^\s*$', '', comment, 0, re.MULTILINE)

            self.start_ip = 0
            self.end_ip = 0

            # move this code to an async task so the browser doesn't hang
            try:
                lookup = socket.gethostbyname_ex(self.name)
                hostname = lookup[0]
                aliases = re.sub('[\[\]\']', '', str(lookup[1]))
                ips = re.sub('[\[\]\']', '', str(lookup[2]))

                self.comment = \
                    comment + "\r\n" + \
                    "__hostname: " + hostname + "\r\n" + \
                    "__aliases: " + aliases + "\r\n" + \
                    "__ips: " + ips
            except:
                self.comment = comment + "\r\n" + "__iplookup failed for " + self.name

web/templates/web/asset_confirm_delete.html
{% extends "base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Asset</legend>
                <h2>Are you sure you want to delete the Asset "{{ object.name }}"</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'assma-home' %}">Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %}

web/templates/web/asset_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="container">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Create or Update Asset</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Submit</button>
            </div>
        </form>
    </div>
{% endblock content %}

web/templates/web/asset_list.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div>
    <h1>Assets</h1>
    <table class="table table-bordered table-condensed">
        <tr>
            <th>Name</th>
            <th>Org</th>
            <th>Type</th>
            <th>Comment</th>
            <th>Created</th>
            <th>Modified</th>
            {% if perms.web.delete_asset %}
            <th>Modify</th>
            {% endif %}
        </tr>
        {% for object in object_list %}
        <tr>
            <td>{{object.name}}</td>
            <td>{{object.org}}</td>
            <td>{{object.type}}</td>
            <td>{{object.comment|linebreaks}}</td>
            <td>{{object.created|date:"Y-m-d H:i:s"}}</td>
            <td>{{object.modified|date:"Y-m-d H:i:s"}}</td>
            {% if perms.web.delete_asset %}
            <td><a href="{% url 'asset-update' object.id %}">update</a>
                <a href="{% url 'asset-delete' object.id %}">delete</a>
            </td>
            {% endif %}
        </tr>
        {% endfor %}

    </table>
    {% if is_paginated %}
      {% if page_obj.has_previous %}
        <a class="btn btn-outline-info mb-4" href="?{% for key,value in request.GET.items %}{% if key != 'page' %}{{ key }}={{ value }}&{% endif %}{% endfor %}page=1">First</a>
        <a class="btn btn-outline-info mb-4" href="?{% for key,value in request.GET.items %}{% if key != 'page' %}{{ key }}={{ value }}&{% endif %}{% endfor %}page={{ page_obj.previous_page_number }}">Previous</a>
      {% endif %}
      {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
          <a class="btn btn-info mb-4" href="?{% for key,value in request.GET.items %}{% if key != 'page' %}{{ key }}={{ value }}&{% endif %}{% endfor %}page={{ num }}">{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
          <a class="btn btn-outline-info mb-4" href="?{% for key,value in request.GET.items %}{% if key != 'page' %}{{ key }}={{ value }}&{% endif %}{% endfor %}page={{ num }}">{{ num }}</a>
        {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        <a class="btn btn-outline-info mb-4" href="?{% for key,value in request.GET.items %}{% if key != 'page' %}{{ key }}={{ value }}&{% endif %}{% endfor %}page={{ page_obj.next_page_number }}">Next</a>
        <a class="btn btn-outline-info mb-4" href="?{% for key,value in request.GET.items %}{% if key != 'page' %}{{ key }}={{ value }}&{% endif %}{% endfor %}page={{ page_obj.paginator.num_pages }}">Last</a>
      {% endif %}
    {% endif %}
</div>
{% endblock content %}

web/templates/web/org_confirm_delete.html
{% extends "base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Org</legend>
                <h2>Are you sure you want to delete the Organisation "{{ object.name }}"</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'assma-home' %}">Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %}

web/templates/web/org_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Create or Update Org</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Submit</button>
        </div>
    </form>
</div>
{% endblock content %}

web/templates/web/org_list.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div>
    <h1>Orgs</h1>
    <table class="table table-bordered table-condensed">
        <tr>
            <th>Name</th>
            <th>Sector</th>
            <th>Level</th>
            <th>Tier</th>
            <th>coid</th>
            <th>Comment</th>
            <th>Created</th>
            <th>Modified</th>
            {% if perms.web.delete_org %}
            <th>Modify</th>
            {% endif %}
        </tr>
        {% for object in object_list %}
        <tr>
            <td>{{object.name}}</td>
            <td>{{object.sector}}</td>
            <td>{{object.level}}</td>
            <td>{{object.tier}}</td>
            <td>{{object.id}}</td>
            <td>{{object.comment|linebreaks}}</td>
            <td>{{object.created|date:"Y-m-d H:i:s"}}</td>
            <td>{{object.modified|date:"Y-m-d H:i:s"}}</td>
            {% if perms.web.delete_org %}
            <td><a href="{% url 'org-update' object.id %}">update</a>
                <br>
                <a href="{% url 'org-delete' object.id %}">delete</a>
            </td>
            {% endif %}
        </tr>
        {% endfor %}

    </table>
    {% if is_paginated %}
      {% if page_obj.has_previous %}
        <a class="btn btn-outline-info mb-4" href="?{% for key,value in request.GET.items %}{% if key != 'page' %}{{ key }}={{ value }}&{% endif %}{% endfor %}page=1">First</a>
        <a class="btn btn-outline-info mb-4" href="?{% for key,value in request.GET.items %}{% if key != 'page' %}{{ key }}={{ value }}&{% endif %}{% endfor %}page={{ page_obj.previous_page_number }}">Previous</a>
      {% endif %}
      {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
          <a class="btn btn-info mb-4" href="?{% for key,value in request.GET.items %}{% if key != 'page' %}{{ key }}={{ value }}&{% endif %}{% endfor %}page={{ num }}">{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
          <a class="btn btn-outline-info mb-4" href="?{% for key,value in request.GET.items %}{% if key != 'page' %}{{ key }}={{ value }}&{% endif %}{% endfor %}page={{ num }}">{{ num }}</a>
        {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        <a class="btn btn-outline-info mb-4" href="?{% for key,value in request.GET.items %}{% if key != 'page' %}{{ key }}={{ value }}&{% endif %}{% endfor %}page={{ page_obj.next_page_number }}">Next</a>
        <a class="btn btn-outline-info mb-4" href="?{% for key,value in request.GET.items %}{% if key != 'page' %}{{ key }}={{ value }}&{% endif %}{% endfor %}page={{ page_obj.paginator.num_pages }}">Last</a>
      {% endif %}
    {% endif %}
</div>
{% endblock content %}

web/templates/web/org_search.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content%}
<div class="container">
    <h2>Org Search</h2>
    <form class="form-group col-sm-2 col-md-10" action="" method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-outline-info" type="submit">Search</button>
    </form>
</div>
{% endblock %}

web/templates/web/search.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content%}
<div class="container">
    <h2>Search</h2>
    <form class="form-group col-sm-2 col-md-10" action="" method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-outline-info" type="submit">Search</button>
    </form>
</div>
{% endblock %}