api/urls.py
from django.urls import include, path
from rest_framework.routers import DefaultRouter
from rest_framework.schemas import get_schema_view
from rest_framework.documentation import include_docs_urls

from .views import OrgViewSet, AssetViewSet


router = DefaultRouter()
router.register('v1/org', OrgViewSet, 'api_org_list')
router.register('v1/asset', AssetViewSet, 'api_asset_list')
schema_view = get_schema_view(title='Assma API',
                              description='An API to query orgs or assets',
                              version=1
                              )


urlpatterns = [
    path('api/', include(router.urls)),
    path('api/schema/', schema_view),
    path('api/docs/', include_docs_urls(title='Assma API')),
]

assma/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('web.urls')),
    path('', include('api.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

web/models.py
from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
import ipaddress
import re
import validators
import socket

class Org(models.Model):

    LEVEL_FEDERAL = 'Federal'
    LEVEL_STATE = 'State'
    LEVEL = [
        (LEVEL_FEDERAL, 'Federal / National level'),
        (LEVEL_STATE, 'State level'),
    ]

    SECTOR_ENERGY = 'Energy, Utilities, Agriculture'
    SECTOR_SECURITY = 'Safety and Security'
    SECTOR_DEFENSE = 'Defense and Intelligence'
    SECTOR_ICT = 'ICT'
    SECTOR_TRANSPORTATION = 'Transportation'
    SECTOR_ADMIN = 'Government Administration'
    SECTOR_EDUCATION = 'Education'
    SECTOR_MEDIA = 'Media, Entertainment'
    SECTOR_FINANCE = 'Finance and Economy'
    SECTOR_SPECIAL = 'Special'
    SECTOR_HEALTH = 'Healthcare'
    SECTOR_MANUFACTURING = 'Manufacturing, Construction'
    SECTOR = [
        (SECTOR_ENERGY, 'Energy, Utilities, Agriculture'),
        (SECTOR_SECURITY, 'Safety and Security'),
        (SECTOR_DEFENSE, 'Defense and Intelligence'),
        (SECTOR_ICT, 'ICT'),
        (SECTOR_TRANSPORTATION, 'Transportation'),
        (SECTOR_ADMIN, 'Government Administration'),
        (SECTOR_EDUCATION, 'Education'),
        (SECTOR_MEDIA, 'Media, Entertainment'),
        (SECTOR_FINANCE, 'Finance and Economy'),
        (SECTOR_SPECIAL, 'Special'),
        (SECTOR_HEALTH, 'Healthcare'),
        (SECTOR_MANUFACTURING, 'Manufacturing, Construction'),
    ]

    name = models.CharField(max_length=255, null=False, unique=True)
    level = models.CharField(max_length=255, choices=LEVEL, default=LEVEL_FEDERAL)
    sector = models.CharField(max_length=255, choices=SECTOR, default=SECTOR_ADMIN)
    tier = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)], default=5)
    comment = models.TextField(blank=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Asset(models.Model):
    TYPE_DOMAIN = 'domain'
    TYPE_IPV4 = 'ipv4'
    TYPE_RANGE4 = 'range4'
    TYPE_NETMASK4 = 'netmask4'
    TYPE_CIDR4 = 'cidr4'
    TYPE_IPV6 = 'ipv6'
    TYPE_RANGE6 = 'range6'
    TYPE_CIDR6 = 'cidr6'
    TYPE = [
        (TYPE_DOMAIN, 'domain'),
        (TYPE_IPV4, 'ipv4'),
        (TYPE_RANGE4, 'range4'),
        (TYPE_NETMASK4, 'netmask4'),
        (TYPE_CIDR4, 'cidr4'),
        (TYPE_IPV6, 'ipv6'),
        (TYPE_RANGE6, 'range6'),
        (TYPE_CIDR6, 'cidr6'),
    ]

    name = models.CharField(max_length=255, null=False, unique=True)
    org = models.ForeignKey(Org, on_delete=models.PROTECT)
    type = models.CharField(max_length=255, choices=TYPE)
    start_ip = models.UUIDField(blank=True)
    end_ip = models.UUIDField(blank=True)
    comment = models.TextField(blank=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def save(self, **kwargs):
        self.clean()
        return super(Asset, self).save(**kwargs)

    def clean(self):
        super(Asset, self).clean()

        if str(self.type) == "ipv4":
            try:
                ipaddress.IPv4Address(str(self.name))
            except:
                raise ValidationError('\"' + self.name + '\" is not a valid ipv4 address')
            self.start_ip = int(ipaddress.IPv4Address(self.name))
            self.end_ip = int(ipaddress.IPv4Address(self.name))

        if str(self.type) == "ipv6":
            try:
                ipaddress.IPv6Address(str(self.name))
            except:
                raise ValidationError('\"' + self.name + '\" is not a valid ipv6 address')
            self.start_ip = int(ipaddress.IPv6Address(self.name))
            self.end_ip = int(ipaddress.IPv6Address(self.name))

        if str(self.type) == "cidr4":
            match = re.search('/', self.name,  )
            if match:
                try:
                    ipaddress.IPv4Network(str(self.name))
                except:
                    raise ValidationError('\"' + self.name + '\" is not a valid ipv4 network address')
                self.start_ip = int(ipaddress.IPv4Network(self.name)[0])
                self.end_ip = int(ipaddress.IPv4Network(self.name)[-1])
            else:
                raise ValidationError('\"' + self.name + '\" is not a valid ipv4 cidr address')

        if str(self.type) == "cidr6":
            try:
                ipaddress.IPv6Network(str(self.name))
            except:
                raise ValidationError('\"' + self.name + '\" is not a valid ipv6 cidr address')
            self.start_ip = int(ipaddress.IPv6Network(self.name)[0])
            self.end_ip = int(ipaddress.IPv6Network(self.name)[-1])

        if str(self.type) == "range4":
            match = re.search('[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}-[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}', self.name,  )
            if match:
                pair = self.name.split("-")
                test = ipaddress.IPv4Address(pair[1]) > ipaddress.IPv4Address(pair[0])
                if test == False:
                    raise ValidationError('\"' + pair[1] + '\" is not higher than \"' + pair[0] + '\" try again!')

                for ip4 in pair:
                    try:
                        ipaddress.IPv4Address(str(ip4))
                    except:
                        raise ValidationError('\"' + ip4 + '\" is not a valid ipv4 address')
                self.start_ip = int(ipaddress.IPv4Address(pair[0]))
                self.end_ip = int(ipaddress.IPv4Address(pair[1]))
            else:
                raise ValidationError('\"' + self.name + '\" is not a valid range4 address, please use a hyphen as a separator eg 1.2.3.4-1.2.3.8')

        if str(self.type) == "range6":
            match = re.search('[0-9a-f:]+-[0-9a-f:]+', self.name, re.I)
            if match:
                pair = self.name.split("-")
                test = ipaddress.IPv6Address(pair[1]) > ipaddress.IPv6Address(pair[0])
                if test == False:
                    raise ValidationError('\"' + pair[1] + '\" is not higher than \"' + pair[0] + '\" try again!')
                for ip6 in pair:
                    try:
                        ipaddress.IPv6Address(str(ip6))
                    except:
                        raise ValidationError('\"' + ip6 + '\" is not a valid ipv6 address')
                self.start_ip = int(ipaddress.IPv6Address(pair[0]))
                self.end_ip = int(ipaddress.IPv6Address(pair[1]))
            else:
                raise ValidationError('\"' + self.name + '\" is not a valid range6 address, please use a hyphen as a separator eg 2001:db8::-2001:db8:0000:0000:0000:0000:0000:00ff')

        if str(self.type) == "netmask4":
            match = re.search('[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}/[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}', self.name,  )
            if match:
                try:
                    ipaddress.IPv4Network(str(self.name))
                except:
                    raise ValidationError('\"' + self.name + '\" is not a valid ipv4 netmask, please use forward slash as separator eg 192.168.10.0/255.255.255.0')
                self.start_ip = int(ipaddress.IPv4Network(self.name)[0])
                self.end_ip = int(ipaddress.IPv4Network(self.name)[-1])
            else:
                raise ValidationError('\"' + self.name + '\" is not a valid ipv4 netmask, please use forward slash as separator eg 192.168.10.0/255.255.255.0')

        if str(self.type) == "domain":
            test = validators.domain(self.name)
            if test != True:
                raise ValidationError('\"' + self.name + '\" is not a valid domain name')

            # remove old lookup results ready for new one
            comment = re.sub('^__.*$', '', self.comment, 0, re.MULTILINE)
            # remove blank lines
            comment = re.sub(r'^\s*$', '', comment, 0, re.MULTILINE)

            self.start_ip = 0
            self.end_ip = 0

            # move this code to an async task so the browser doesn't hang
            try:
                lookup = socket.gethostbyname_ex(self.name)
                hostname = lookup[0]
                aliases = re.sub('[\[\]\']', '', str(lookup[1]))
                ips = re.sub('[\[\]\']', '', str(lookup[2]))

                self.comment = \
                    comment + "\r\n" + \
                    "__hostname: " + hostname + "\r\n" + \
                    "__aliases: " + aliases + "\r\n" + \
                    "__ips: " + ips
            except:
                self.comment = comment + "\r\n" + "__iplookup failed for " + self.name

assma/templates/about.html
{% extends "base.html" %}
{% block content %}
<h1>Assma About Page</h1>

<h3>API Quick start guide</h3>
List all assets<br>
curl -s -k -H "Authorization: Token your-api-key"  -H "content-type: application/json" https://hostname:port/api/v1/asset/<br>
<br>
List all orgs<br>
curl -s -k -H "Authorization: Token your-api-key"  -H "content-type: application/json" https://hostname:port/api/v1/org/<br>
<br>
List one asset - by asset_id<br>
curl -s -k -H "Authorization: Token your-api-key"  -H "content-type: application/json" https://hostname:port/api/v1/asset/1/<br>
<br>
List one org by org id<br>
curl -s -k -H "Authorization: Token your-api-key"  -H "content-type: application/json" https://hostname:port/api/v1/org/1/<br>
<br>
Search orgs (exact match) by name, id, level, tier, (partial match) by name_like, comment<br>
curl -s -k -H "Authorization: Token your-api-key"  -H "content-type: application/json" https://hostname:port/api/v1/org/?name=1.2.3.4<br>
<br>
Search assets (exact match) by org, org_id, name, id, type, (partial match) by org_like, name_like, comment<br>
curl -s -k -H "Authorization: Token your-api-key"  -H "content-type: application/json" https://hostname:port/api/v1/asset/?type=ipv4<br>
<br>
Create new org<br>
curl -X POST -s -k -H "Authorization: Token your-api-key"  -H "content-type: application/json" http://127.0.0.1:8000/api/v1/org/ -d '{"name":"new org 25", "level": "National", "sector": "ICT", "tier": 5, "comment": "hi"}'<br>
<br>
Create new asset (must know the org_id)<br>
curl -X POST -s -k -H "Authorization: Token your-api-key"  -H "content-type: application/json" http://127.0.0.1:8000/api/v1/asset/ -d '{"name":"8.8.8.8", "type":"ipv4", "org":5}'<br>
<br>
Delete org by org id (successful delete returns a 204 No Content)<br>
This will fail if the org has assets related to it. Assets related to an org must be deleted first before the org will delete successfully<br>
curl -X DELETE -s -k -H "Authorization: Token your-api-key"  -H "content-type: application/json" http://127.0.0.1:8000/api/v1/org/5/<br>
<br>
Delete asset by asset id (successful delete returns a 204 No Content)<br>
curl -X DELETE -s -k -H "Authorization: Token your-api-key"  -H "content-type: application/json" http://127.0.0.1:8000/api/v1/asset/7/<br>

{% endblock content %}

assma/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">

    <title>Assma</title>

</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container-fluid">
            <!--
          <a class="navbar-brand mr-4" href="{% url 'assma-home' %}">Assma</--a>
          -->
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{% url 'assma-home' %}">Home</a>
              <a class="nav-item nav-link" href="{% url 'assma-about' %}">About</a>
              {% if user.is_superuser %}
              <a class="nav-item nav-link" href="/admin/">Admin</a>
              {% endif %}
           </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if user.is_authenticated %}
                <a class="nav-item nav-link" href="{% url 'profile' %}">{{ user.username }}'s Profile</a>
                <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
              {% else %}
                <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container-fluid">
      <div class="row">
        <div class="col-md-2">
          <div class="content-section">
            <h3>Assma</h3>
            <p class='text-muted'>Quick links
              <ul class="list-group">
                  {% if user.is_authenticated %}
                <a class="btn btn-secondary btn-color btn-sm mt-1 mb-1" href="{% url 'org-list' %}">List Orgs</a>
                <a class="btn btn-secondary btn-color btn-sm mt-1 mb-1" href="{% url 'org-search' %}">Search Orgs</a>
                {% if perms.web.add_org %}
                <a class="btn btn-secondary btn-color btn-sm mt-1 mb-1" href="{% url 'org-create' %}">New Org</a>
                {% endif %}
                <br>
                <a class="btn btn-secondary btn-color btn-sm mt-1 mb-1" href="{% url 'asset-list' %}">List Assets</a>
                <a class="btn btn-secondary btn-color btn-sm mt-1 mb-1" href="{% url 'asset-search' %}">Search Assets</a>
                {% if perms.web.add_asset %}
                <a class="btn btn-secondary btn-color btn-sm mt-1 mb-1" href="{% url 'asset-create' %}">New Asset</a>
                {% endif %}
                <br>
                <a class="btn btn-secondary btn-color btn-sm mt-1 mb-1" href="{% url 'api-root' %}">API Explore</a>
                <a class="btn btn-secondary btn-color btn-sm mt-1 mb-1" href="/api/docs/">API Docs</a>
                <a class="btn btn-secondary btn-color btn-sm mt-1 mb-1" href="/api/schema">API Schema</a>
                <a class="btn btn-secondary btn-color btn-sm mt-1 mb-1" href="/api/docs/#users-api-token-auth-create">API Token</a>
                  {% endif %}
              </ul>
            </p>
          </div>
        </div>

        <div class="col-md-10">
          {% if messages %}
            {% for message in messages %}
              <div class="alert alert-{{ message.tags }}">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}
          {% block content %}{% endblock %}
        </div>


      </div>
    </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

assma/templates/home.html
{% extends "base.html" %}
{% block content %}
{% if user.is_authenticated %}
    <h2>Recent Org updates</h2>
    <table class="table table-bordered table-condensed">
        <tr>
            <th>Name</th>
            <th>Sector</th>
            <th>Level</th>
            <th>Tier</th>
            <th>coid</th>
            <th>Comment</th>
            <th>Created</th>
            <th>Modified</th>
            {% if perms.web.change_org %}
            <th>Modify</th>
            {% endif %}
        </tr>
        {% for org in orgs %}
        <tr>
            <td>{{org.name}}</td>
            <td>{{org.sector}}</td>
            <td>{{org.level}}</td>
            <td>{{org.tier}}</td>
            <td>{{org.id}}</td>
            <td>{{org.comment|linebreaks}}</td>
            <td>{{org.created|date:"Y-m-d H:i:s"}}</td>
            <td>{{org.modified|date:"Y-m-d H:i:s"}}</td>
            {% if perms.web.change_org %}
            <td><a href="{% url 'org-update' org.id %}">update</a>
                <a href="{% url 'org-delete' org.id %}">delete</a>
            </td>
            {% endif %}
        </tr>
        {% endfor %}

    </table>
<br>
    <h2>Recent Asset updates</h2>
    <table class="table table-bordered table-condensed">
        <tr>
            <th>Name</th>
            <th>Org</th>
            <th>Type</th>
            <th>Comment</th>
            <th>Created</th>
            <th>Modified</th>
            {% if perms.web.change_asset %}
            <th>Modify</th>
            {% endif %}
        </tr>
        {% for asset in assets %}
        <tr>
            <td>{{asset.name}}</td>
            <td>{{asset.org}}</td>
            <td>{{asset.type}}</td>
            <td>{{asset.comment|linebreaks}}</td>
            <td>{{asset.created|date:"Y-m-d H:i:s"}}</td>
            <td>{{asset.modified|date:"Y-m-d H:i:s"}}</td>
            {% if perms.web.change_asset %}
            <td><a href="{% url 'asset-update' asset.id %}">update</a>
                <a href="{% url 'asset-delete' asset.id %}">delete</a>
            </td>
            {% endif %}
        </tr>
        {% endfor %}

    </table>
{% else %}
Please login to use assma
{% endif %}
{% endblock content %}